
export  const REGISTER_USER_REQUEST="REGISTER_USER_REQUEST";
export  const REGISTER_USER_SUCCESS="REGISTER_USER_SUCCESS";
export  const REGISTER_USER_FAIL="REGISTER_USER_FAIL";

export  const LOGIN_USER_REQUEST="LOGIN_USER_REQUEST";
export  const LOGIN_USER_SUCCESS="LOGIN_USER_SUCCESS";
export  const LOGIN_USER_FAIL="LOGIN_USER_FAIL";


export  const All_STUDENT_REQUEST="All_STUDENT_REQUEST";
export  const All_STUDENT_SUCCESS="All_STUDENT_SUCCESS";
export  const All_STUDENT_FAIL="All_STUDENT_FAIL";

export const NEW_STUDENT_REQUEST = "NEW_STUDENT_REQUEST";
export const NEW_STUDENT_SUCCESS = "NEW_STUDENT_SUCCESS";
export const NEW_STUDENT_RESET = "NEW_STUDENT_RESET";
export const NEW_STUDENT_FAIL = "NEW_STUDENT_FAIL";

export const UPDATE_STUDENT_REQUEST = "UPDATE_STUDENT_REQUEST";
export const UPDATE_STUDENT_SUCCESS = "UPDATE_STUDENT_SUCCESS";
export const UPDATE_STUDENT_RESET = "UPDATE_STUDENT_RESET";
export const UPDATE_STUDENT_FAIL = "UPDATE_STUDENT_FAIL";

export const DELETE_STUDENT_REQUEST = "DELETE_STUDENT_REQUEST";
export const DELETE_STUDENT_SUCCESS = "DELETE_STUDENT_SUCCESS";
export const DELETE_STUDENT_RESET = "DELETE_STUDENT_RESET";
export const DELETE_STUDENT_FAIL = "DELETE_STUDENT_FAIL";


export const CLEAR_ERRORS = "CLEAR_ERRORS";